# Generated by Django 4.2 on 2025-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
